# Generated by Django 4.0.2 on 2022-03-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groomingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detaildb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=100)),
                ('visits', models.IntegerField()),
                ('fileupload', models.FileField(upload_to='required_details')),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='petdb',
            name='state',
        ),
    ]
